// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EvCoOwnership.Repositories.Models;

public partial class Configuration
{
    public string Key { get; set; }

    public string Value { get; set; }

    public string Description { get; set; }

    public DateTime? UpdatedAt { get; set; }
}