// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EvCoOwnership.Repositories.Enums;

namespace EvCoOwnership.Repositories.Models;

public partial class ContractTemplate
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Version { get; set; }

    public string Description { get; set; }

    public string Content { get; set; }

    public string TermsAndConditions { get; set; }

    public EContractTemplateStatus? StatusEnum { get; set; }

    public int? CreatedBy { get; set; }

    public int? ApprovedBy { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User ApprovedByNavigation { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<GroupContract> GroupContracts { get; set; } = new List<GroupContract>();
}