// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EvCoOwnership.Repositories.Models;

public partial class CoOwner
{
    public int UserId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<DrivingLicense> DrivingLicenses { get; set; } = new List<DrivingLicense>();

    public virtual ICollection<FundAddition> FundAdditions { get; set; } = new List<FundAddition>();

    public virtual User User { get; set; }

    public virtual ICollection<VehicleContract> VehicleContracts { get; set; } = new List<VehicleContract>();
}