// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EvCoOwnership.Repositories.Enums;

namespace EvCoOwnership.Repositories.Models;

public partial class DrivingLicense
{
    public int Id { get; set; }

    public int? CoOwnerId { get; set; }

    public string LicenseNumber { get; set; }

    public string IssuedBy { get; set; }

    public DateOnly IssueDate { get; set; }

    public DateOnly? ExpiryDate { get; set; }

    public string LicenseImageUrl { get; set; }

    /// <summary>
    /// Verification status of the driving license
    /// </summary>
    public EDrivingLicenseVerificationStatus VerificationStatus { get; set; } = EDrivingLicenseVerificationStatus.Pending;

    /// <summary>
    /// Reason for rejection if the license is rejected
    /// </summary>
    public string RejectReason { get; set; }

    /// <summary>
    /// User ID of the admin/staff who approved/rejected the license
    /// </summary>
    public int? VerifiedByUserId { get; set; }

    /// <summary>
    /// Date and time when the license was verified (approved/rejected)
    /// </summary>
    public DateTime? VerifiedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual CoOwner CoOwner { get; set; }

    public virtual User VerifiedByUser { get; set; }
}