// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EvCoOwnership.Repositories.Models;

public partial class DrivingLicense
{
    public int Id { get; set; }

    public int? CoOwnerId { get; set; }

    public string LicenseNumber { get; set; }

    public string IssuedBy { get; set; }

    public DateOnly IssueDate { get; set; }

    public DateOnly? ExpiryDate { get; set; }

    public string LicenseImageUrl { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual CoOwner CoOwner { get; set; }
}