// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EvCoOwnership.Repositories.Models;

public partial class FileUpload
{
    public int Id { get; set; }

    public byte[] Data { get; set; }

    public string FileName { get; set; }

    public string MimeType { get; set; }

    public DateTime? UploadedAt { get; set; }
}