// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EvCoOwnership.Repositories.Enums;

namespace EvCoOwnership.Repositories.Models;

public partial class FundUsage
{
    public int Id { get; set; }

    public int? FundId { get; set; }

    public EUsageType? UsageTypeEnum { get; set; }

    public decimal Amount { get; set; }

    public string Description { get; set; }

    public string ImageUrl { get; set; }

    public int? MaintenanceCostId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Fund Fund { get; set; }

    public virtual ICollection<FundUsageVote> FundUsageVotes { get; set; } = new List<FundUsageVote>();

    public virtual MaintenanceCost MaintenanceCost { get; set; }

    public virtual ICollection<VehicleUpgradeProposal> VehicleUpgradeProposals { get; set; } = new List<VehicleUpgradeProposal>();
}