// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EvCoOwnership.Repositories.Enums;

namespace EvCoOwnership.Repositories.Models;

public partial class Group
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int? CreatedBy { get; set; }

    public EGroupStatus? StatusEnum { get; set; }

    public int? MaxMembers { get; set; }

    public EGroupType? GroupTypeEnum { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<GroupContract> GroupContracts { get; set; } = new List<GroupContract>();

    public virtual ICollection<GroupFund> GroupFunds { get; set; } = new List<GroupFund>();

    public virtual ICollection<GroupMember> GroupMembers { get; set; } = new List<GroupMember>();

    public virtual ICollection<GroupVehicle> GroupVehicles { get; set; } = new List<GroupVehicle>();

    public virtual ICollection<GroupVote> GroupVotes { get; set; } = new List<GroupVote>();
}