// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EvCoOwnership.Repositories.Enums;

namespace EvCoOwnership.Repositories.Models;

public partial class GroupFund
{
    public int Id { get; set; }

    public int? GroupId { get; set; }

    public int? FundId { get; set; }

    public decimal? TargetAmount { get; set; }

    public decimal? CurrentAmount { get; set; }

    public string Purpose { get; set; }

    public DateOnly? Deadline { get; set; }

    public EGroupFundStatus? StatusEnum { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Fund Fund { get; set; }

    public virtual Group Group { get; set; }
}