// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EvCoOwnership.Repositories.Enums;

namespace EvCoOwnership.Repositories.Models;

public partial class GroupMember
{
    public int GroupId { get; set; }

    public int UserId { get; set; }

    public EGroupMemberRole? RoleEnum { get; set; }

    public DateTime? JoinedAt { get; set; }

    public decimal? InvestmentAmount { get; set; }

    public decimal? OwnershipPercentage { get; set; }

    public EGroupMemberStatus? StatusEnum { get; set; }

    public virtual Group Group { get; set; }

    public virtual User User { get; set; }
}