// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EvCoOwnership.Repositories.Enums;

namespace EvCoOwnership.Repositories.Models;

public partial class GroupContract
{
    public int Id { get; set; }

    public int? GroupId { get; set; }

    public int? TemplateId { get; set; }

    public string Name { get; set; }

    public string Version { get; set; }

    public string Content { get; set; }

    public string TermsAndConditions { get; set; }

    public EEContractStatus? StatusEnum { get; set; }

    public DateOnly EffectiveDate { get; set; }

    public DateOnly? ExpiryDate { get; set; }

    public DateOnly? TerminationDate { get; set; }

    public int? CreatedBy { get; set; }

    public int? ApprovedBy { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public string Notes { get; set; }

    public string AttachmentUrls { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User ApprovedByNavigation { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Group Group { get; set; }

    public virtual ContractTemplate Template { get; set; }
}