// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EvCoOwnership.Repositories.Enums;

namespace EvCoOwnership.Repositories.Models;

public partial class GroupVehicle
{
    public int GroupId { get; set; }

    public int VehicleId { get; set; }

    public DateTime? AddedAt { get; set; }

    public EGroupStatus? StatusEnum { get; set; }

    public virtual Group Group { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}