// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EvCoOwnership.Repositories.Enums;

namespace EvCoOwnership.Repositories.Models;

public partial class GroupVote
{
    public int Id { get; set; }

    public int? GroupId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public EGroupVoteType? VoteTypeEnum { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public EGroupVoteStatus? StatusEnum { get; set; }

    public decimal? RequiredApprovalPercentage { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Group Group { get; set; }

    public virtual ICollection<GroupVoteResponse> GroupVoteResponses { get; set; } = new List<GroupVoteResponse>();
}