// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EvCoOwnership.Repositories.Models;

public partial class GroupVoteResponse
{
    public int VoteId { get; set; }

    public int UserId { get; set; }

    public bool IsAgree { get; set; }

    public string Comments { get; set; }

    public DateTime? VotedAt { get; set; }

    public virtual User User { get; set; }

    public virtual GroupVote Vote { get; set; }
}