// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EvCoOwnership.Repositories.Models;

public partial class NotificationEntity
{
    public int Id { get; set; }

    public string NotificationType { get; set; }

    public string AdditionalData { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<UserNotification> UserNotifications { get; set; } = new List<UserNotification>();
}