// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EvCoOwnership.Repositories.Enums;

namespace EvCoOwnership.Repositories.Models;

public partial class Role
{
    public int Id { get; set; }

    public EUserRole RoleNameEnum { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}