// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EvCoOwnership.Repositories.Models;

public partial class UserNotification
{
    public int Id { get; set; }

    public int? NotificationId { get; set; }

    public int? UserId { get; set; }

    public DateTime? ReadAt { get; set; }

    public virtual NotificationEntity Notification { get; set; }

    public virtual User User { get; set; }
}