// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EvCoOwnership.Repositories.Enums;

namespace EvCoOwnership.Repositories.Models;

public partial class User
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string NormalizedEmail { get; set; }

    public string PasswordHash { get; set; }

    public string PasswordSalt { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Phone { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string Address { get; set; }

    public string ProfileImageUrl { get; set; }

    public EUserRole? RoleEnum { get; set; }

    public EUserStatus? StatusEnum { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<CheckIn> CheckIns { get; set; } = new List<CheckIn>();

    public virtual ICollection<CheckOut> CheckOuts { get; set; } = new List<CheckOut>();

    public virtual CoOwner CoOwner { get; set; }

    public virtual ICollection<ContractTemplate> ContractTemplateApprovedByNavigations { get; set; } = new List<ContractTemplate>();

    public virtual ICollection<ContractTemplate> ContractTemplateCreatedByNavigations { get; set; } = new List<ContractTemplate>();

    public virtual ICollection<DrivingLicense> DrivingLicenses { get; set; } = new List<DrivingLicense>();

    public virtual ICollection<FundUsageVote> FundUsageVotes { get; set; } = new List<FundUsageVote>();

    public virtual ICollection<GroupContract> GroupContractApprovedByNavigations { get; set; } = new List<GroupContract>();

    public virtual ICollection<GroupContract> GroupContractCreatedByNavigations { get; set; } = new List<GroupContract>();

    public virtual ICollection<GroupMember> GroupMembers { get; set; } = new List<GroupMember>();

    public virtual ICollection<GroupVoteResponse> GroupVoteResponses { get; set; } = new List<GroupVoteResponse>();

    public virtual ICollection<GroupVote> GroupVotes { get; set; } = new List<GroupVote>();

    public virtual ICollection<Group> Groups { get; set; } = new List<Group>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<UserNotification> UserNotifications { get; set; } = new List<UserNotification>();

    public virtual UserRefreshToken UserRefreshToken { get; set; }

    public virtual ICollection<VehicleCondition> VehicleConditions { get; set; } = new List<VehicleCondition>();

    public virtual ICollection<VehicleUpgradeProposal> VehicleUpgradeProposals { get; set; } = new List<VehicleUpgradeProposal>();

    public virtual ICollection<VehicleUpgradeVote> VehicleUpgradeVotes { get; set; } = new List<VehicleUpgradeVote>();

    public virtual ICollection<VehicleUsageRecord> VehicleUsageRecords { get; set; } = new List<VehicleUsageRecord>();

    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
}