// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EvCoOwnership.Repositories.Models;

/// <summary>
/// Records actual vehicle usage data for each trip (check-in to check-out)
/// </summary>
public partial class VehicleUsageRecord
{
    public int Id { get; set; }

    /// <summary>
    /// Reference to the booking that generated this usage
    /// </summary>
    public int? BookingId { get; set; }

    /// <summary>
    /// Reference to the vehicle used
    /// </summary>
    public int? VehicleId { get; set; }

    /// <summary>
    /// Reference to the co-owner who used the vehicle
    /// </summary>
    public int? CoOwnerId { get; set; }

    /// <summary>
    /// Reference to check-in record
    /// </summary>
    public int? CheckInId { get; set; }

    /// <summary>
    /// Reference to check-out record
    /// </summary>
    public int? CheckOutId { get; set; }

    /// <summary>
    /// When the trip started (check-in time)
    /// </summary>
    public DateTime StartTime { get; set; }

    /// <summary>
    /// When the trip ended (check-out time)
    /// </summary>
    public DateTime EndTime { get; set; }

    /// <summary>
    /// Total duration of the trip in hours (calculated)
    /// </summary>
    public decimal DurationHours { get; set; }

    /// <summary>
    /// Distance traveled in kilometers (from odometer readings)
    /// </summary>
    public int? DistanceKm { get; set; }

    /// <summary>
    /// Battery percentage used during trip
    /// </summary>
    public int? BatteryUsedPercent { get; set; }

    /// <summary>
    /// Odometer reading at check-in
    /// </summary>
    public int? OdometerStart { get; set; }

    /// <summary>
    /// Odometer reading at check-out
    /// </summary>
    public int? OdometerEnd { get; set; }

    /// <summary>
    /// Battery level at check-in
    /// </summary>
    public int? BatteryLevelStart { get; set; }

    /// <summary>
    /// Battery level at check-out
    /// </summary>
    public int? BatteryLevelEnd { get; set; }

    /// <summary>
    /// Base booking cost
    /// </summary>
    public decimal? BookingCost { get; set; }

    /// <summary>
    /// Late fee charged (if any)
    /// </summary>
    public decimal? LateFee { get; set; }

    /// <summary>
    /// Damage charges (if any)
    /// </summary>
    public decimal? DamageFee { get; set; }

    /// <summary>
    /// Total cost for this trip
    /// </summary>
    public decimal? TotalCost { get; set; }

    /// <summary>
    /// Purpose of the trip (from booking)
    /// </summary>
    public string Purpose { get; set; }

    /// <summary>
    /// Additional notes about the trip
    /// </summary>
    public string Notes { get; set; }

    /// <summary>
    /// Whether this was a QR self-service check-in/out
    /// </summary>
    public bool? WasQRScanned { get; set; }

    /// <summary>
    /// Staff who assisted (if manual check-in/out)
    /// </summary>
    public int? AssistingStaffId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    // Navigation properties
    public virtual Booking Booking { get; set; }

    public virtual Vehicle Vehicle { get; set; }

    public virtual CoOwner CoOwner { get; set; }

    public virtual CheckIn CheckIn { get; set; }

    public virtual CheckOut CheckOut { get; set; }

    public virtual User AssistingStaff { get; set; }
}
