// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EvCoOwnership.Repositories.Models;

public partial class VehicleUsageRecord
{
    public int Id { get; set; }

    public int? BookingId { get; set; }

    public int? VehicleId { get; set; }

    public int? CoOwnerId { get; set; }

    public int? CheckInId { get; set; }

    public int? CheckOutId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public decimal DurationHours { get; set; }

    public int? DistanceKm { get; set; }

    public int? BatteryUsedPercent { get; set; }

    public int? OdometerStart { get; set; }

    public int? OdometerEnd { get; set; }

    public int? BatteryLevelStart { get; set; }

    public int? BatteryLevelEnd { get; set; }

    public decimal? BookingCost { get; set; }

    public decimal? LateFee { get; set; }

    public decimal? DamageFee { get; set; }

    public decimal? TotalCost { get; set; }

    public string Purpose { get; set; }

    public string Notes { get; set; }

    public bool? WasQrScanned { get; set; }

    public int? AssistingStaffId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User AssistingStaff { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual CheckIn CheckIn { get; set; }

    public virtual CheckOut CheckOut { get; set; }

    public virtual CoOwner CoOwner { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}