// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EvCoOwnership.Repositories.Enums;

namespace EvCoOwnership.Repositories.Models;

public partial class VehicleUpgradeProposal
{
    public int Id { get; set; }

    public int? VehicleId { get; set; }

    public EUpgradeType UpgradeTypeEnum { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public decimal EstimatedCost { get; set; }

    public string Justification { get; set; }

    public string ImageUrl { get; set; }

    public string VendorName { get; set; }

    public string VendorContact { get; set; }

    public DateOnly? ProposedInstallationDate { get; set; }

    public int? EstimatedDurationDays { get; set; }

    public int? ProposedByUserId { get; set; }

    public DateTime ProposedAt { get; set; }

    public string Status { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public DateTime? RejectedAt { get; set; }

    public DateTime? CancelledAt { get; set; }

    public bool? IsExecuted { get; set; }

    public DateTime? ExecutedAt { get; set; }

    public decimal? ActualCost { get; set; }

    public string ExecutionNotes { get; set; }

    public int? FundUsageId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual FundUsage FundUsage { get; set; }

    public virtual User ProposedByUser { get; set; }

    public virtual Vehicle Vehicle { get; set; }

    public virtual ICollection<VehicleUpgradeVote> VehicleUpgradeVotes { get; set; } = new List<VehicleUpgradeVote>();
}