// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EvCoOwnership.Repositories.Enums;

namespace EvCoOwnership.Repositories.Models;

public partial class Vehicle
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Brand { get; set; }

    public string Model { get; set; }

    public int Year { get; set; }

    public string Vin { get; set; }

    public string LicensePlate { get; set; }

    public string Color { get; set; }

    public decimal? BatteryCapacity { get; set; }

    public int? RangeKm { get; set; }

    public DateOnly PurchaseDate { get; set; }

    public decimal PurchasePrice { get; set; }

    public DateOnly? WarrantyUntil { get; set; }

    public int? DistanceTravelled { get; set; }

    public EVehicleStatus? StatusEnum { get; set; }

    public EVehicleVerificationStatus? VerificationStatusEnum { get; set; }

    public decimal? LocationLatitude { get; set; }

    public decimal? LocationLongitude { get; set; }

    public int? CreatedBy { get; set; }

    public int? FundId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual User CreatedByNavigation { get; set; }

    public virtual Fund Fund { get; set; }

    public virtual ICollection<MaintenanceCost> MaintenanceCosts { get; set; } = new List<MaintenanceCost>();

    public virtual ICollection<VehicleCondition> VehicleConditions { get; set; } = new List<VehicleCondition>();

    public virtual ICollection<VehicleContract> VehicleContracts { get; set; } = new List<VehicleContract>();

    public virtual ICollection<VehicleVerificationHistory> VehicleVerificationHistories { get; set; } = new List<VehicleVerificationHistory>();
}