// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EvCoOwnership.Repositories.Enums;

namespace EvCoOwnership.Repositories.Models;

public partial class VehicleVerificationHistory
{
    public int Id { get; set; }

    public int? VehicleId { get; set; }

    public int? StaffId { get; set; }

    public EVehicleVerificationStatus StatusEnum { get; set; }

    public string Notes { get; set; }

    public string Images { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User Staff { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}