// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EvCoOwnership.Repositories.Models;

public partial class VehicleUpgradeVote
{
    public int ProposalId { get; set; }

    public int UserId { get; set; }

    public bool IsAgree { get; set; }

    public string Comments { get; set; }

    public DateTime? VotedAt { get; set; }

    public virtual VehicleUpgradeProposal Proposal { get; set; }

    public virtual User User { get; set; }
}