// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EvCoOwnership.Repositories.Enums;

namespace EvCoOwnership.Repositories.Models;

public partial class VehicleCoOwner
{
    public int CoOwnerId { get; set; }

    public int VehicleId { get; set; }

    public decimal OwnershipPercentage { get; set; }

    public decimal InvestmentAmount { get; set; }

    public EContractStatus? StatusEnum { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual CoOwner CoOwner { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}